### PR TITLE
Setup bump2version

### PR DESCRIPTION
**Pull request by zaro0508**
Setup configs for bump2version[1] to help manage versions.

to update version run..
```
bumpversion patch --config-file setup.cfg
```

[1] https://pypi.org/project/bump2version/

### CODE REVIEW

**Comment by cascadianblue** [comment]
Do you want to add `bumpversion` to `requirements.txt`?

**Comment by zaro0508** [comment]
Added info to README however i don't think it needs to be in requirements.txt because its not needed for testing nor execution of jccli

**Comment by cascadianblue** [comment]
"because its not needed for testing nor execution of jccli"
by that logic, pre-commit (and probably several other dependencies) shouldn't be in requirements.txt either. My impression was that requirements.txt contains all of the tools that a developer might need to work on the project.

**Comment by zaro0508** [comment]
i cannot dispute that logic. the lib has been added.

**Pull request merged**
